import {
  type RemixiconComponentType,
  RiAccountCircleLine,
  RiAppleFill,
  RiAtLine,
  RiAuctionLine,
  RiAwardLine,
  RiBankCardLine,
  RiBankLine,
  RiBasketballLine,
  RiBlueskyFill,
  RiBuildingLine,
  RiCakeLine,
  RiCalendarLine,
  RiCapsuleLine,
  RiCarLine,
  RiChat1Line,
  RiCheckboxLine,
  RiChromeFill,
  RiCodeLine,
  RiCommunityLine,
  RiContactsBookLine,
  RiDiscordFill,
  RiDropboxFill,
  RiDropdownList,
  RiFacebookCircleFill,
  RiFileLine,
  RiFlowerLine,
  RiFolder2Line,
  RiGithubFill,
  RiGlobalLine,
  RiGoogleFill,
  RiGovernmentLine,
  RiGraduationCapLine,
  RiHandHeartLine,
  RiHashtag,
  RiHeartLine,
  RiHomeLine,
  RiHospitalLine,
  RiIdCardLine,
  RiImageLine,
  RiInputField,
  RiInstagramFill,
  RiKeyLine,
  RiLightbulbLine,
  RiLinkedinFill,
  RiLock2Line,
  RiMailLine,
  RiMediumFill,
  RiMentalHealthLine,
  RiMusic2Line,
  RiNewsLine,
  RiParagraph,
  RiPatreonFill,
  RiPhoneLine,
  RiPinterestFill,
  RiPlantLine,
  RiPlaystationFill,
  RiPoliceBadgeLine,
  RiRedditFill,
  RiRestaurantLine,
  RiRobot2Line,
  RiScales3Line,
  RiSchoolLine,
  RiSettings3Line,
  RiShapesLine,
  RiShieldUserLine,
  RiSignpostLine,
  RiSlackFill,
  RiSmartphoneLine,
  RiSnapchatFill,
  RiSofaLine,
  RiSoundcloudFill,
  RiSparklingLine,
  RiSpotifyFill,
  RiStore2Line,
  RiSwitchFill,
  RiSwordLine,
  RiTeamLine,
  RiTentLine,
  RiTiktokFill,
  RiToothLine,
  RiTrophyLine,
  RiTv2Line,
  RiTwitterXFill,
  RiUserLine,
  RiWalletLine,
  RiWhatsappFill,
  RiWindowsFill,
  RiYoutubeFill,
} from "@remixicon/react";

export const ICONS: Record<string, RemixiconComponentType> = {
  account: RiAccountCircleLine,
  bank: RiBankLine,
  basketball: RiBasketballLine,
  building: RiBuildingLine,
  cake: RiCakeLine,
  car: RiCarLine,
  certificate: RiAwardLine,
  chat: RiChat1Line,
  code: RiCodeLine,
  college: RiGraduationCapLine,
  community: RiCommunityLine,
  contacts: RiContactsBookLine,
  creditCard: RiBankCardLine,
  file: RiFileLine,
  flower: RiFlowerLine,
  folder: RiFolder2Line,
  food: RiRestaurantLine,
  gavel: RiAuctionLine,
  giving: RiHandHeartLine,
  global: RiGlobalLine,
  government: RiGovernmentLine,
  heart: RiHeartLine,
  home: RiHomeLine,
  hospital: RiHospitalLine,
  id: RiIdCardLine,
  image: RiImageLine,
  key: RiKeyLine,
  lightbulb: RiLightbulbLine,
  lock: RiLock2Line,
  mail: RiMailLine,
  mentalHealth: RiMentalHealthLine,
  music: RiMusic2Line,
  news: RiNewsLine,
  phone: RiPhoneLine,
  pill: RiCapsuleLine,
  plant: RiPlantLine,
  police: RiPoliceBadgeLine,
  robot: RiRobot2Line,
  scale: RiScales3Line,
  school: RiSchoolLine,
  settings: RiSettings3Line,
  shapes: RiShapesLine,
  signpost: RiSignpostLine,
  smartphone: RiSmartphoneLine,
  socialSecurity: RiShieldUserLine,
  sofa: RiSofaLine,
  sparkles: RiSparklingLine,
  store: RiStore2Line,
  sword: RiSwordLine,
  team: RiTeamLine,
  tent: RiTentLine,
  tooth: RiToothLine,
  trophy: RiTrophyLine,
  tv: RiTv2Line,
  user: RiUserLine,
  wallet: RiWalletLine,

  // Logos
  apple: RiAppleFill,
  bluesky: RiBlueskyFill,
  chrome: RiChromeFill,
  discord: RiDiscordFill,
  dropbox: RiDropboxFill,
  facebook: RiFacebookCircleFill,
  github: RiGithubFill,
  google: RiGoogleFill,
  instagram: RiInstagramFill,
  linkedin: RiLinkedinFill,
  medium: RiMediumFill,
  patreon: RiPatreonFill,
  pinterest: RiPinterestFill,
  playstation: RiPlaystationFill,
  reddit: RiRedditFill,
  slack: RiSlackFill,
  snapchat: RiSnapchatFill,
  soundcloud: RiSoundcloudFill,
  spotify: RiSpotifyFill,
  switch: RiSwitchFill,
  tiktok: RiTiktokFill,
  twitter: RiTwitterXFill,
  whatsapp: RiWhatsappFill,
  windows: RiWindowsFill,
  youtube: RiYoutubeFill,
} as const;
export type Icon = keyof typeof ICONS;

export const JURISDICTIONS = {
  AK: "Alaska",
  AL: "Alabama",
  AR: "Arkansas",
  AZ: "Arizona",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DC: "District of Columbia",
  DE: "Delaware",
  FED: "Federal",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  IA: "Iowa",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  MA: "Massachusetts",
  MD: "Maryland",
  ME: "Maine",
  MI: "Michigan",
  MN: "Minnesota",
  MO: "Missouri",
  MS: "Mississippi",
  MT: "Montana",
  NC: "North Carolina",
  ND: "North Dakota",
  NE: "Nebraska",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NV: "Nevada",
  NY: "New York",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VA: "Virginia",
  VT: "Vermont",
  WA: "Washington",
  WI: "Wisconsin",
  WV: "West Virginia",
  WY: "Wyoming",
} as const;
export type Jurisdiction = keyof typeof JURISDICTIONS;

interface FieldDetails {
  label: string;
  icon: RemixiconComponentType;
}
export const FIELDS: Record<string, FieldDetails> = {
  text: {
    label: "Text",
    icon: RiInputField,
  },
  textarea: {
    label: "Textarea",
    icon: RiParagraph,
  },
  date: {
    label: "Date",
    icon: RiCalendarLine,
  },
  select: {
    label: "Select",
    icon: RiDropdownList,
  },
  checkbox: {
    label: "Checkbox",
    icon: RiCheckboxLine,
  },
  number: {
    label: "Number",
    icon: RiHashtag,
  },
  email: {
    label: "Email",
    icon: RiAtLine,
  },
  phone: {
    label: "Phone",
    icon: RiPhoneLine,
  },
} as const;
export type Field = keyof typeof FIELDS;

export const THEMES = {
  system: "System",
  light: "Light",
  dark: "Dark",
} as const;
export type Theme = keyof typeof THEMES;

export const ROLES = {
  user: "User",
  editor: "Editor",
  admin: "Admin",
} as const;
export type Role = keyof typeof ROLES;
