version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "@vueless/storybook-dark-mode"
        update-types: ["patch", "minor"]

      tiptap:
        patterns:
          - "@tiptap/*"
          - "@namesake/tiptap-extensions"
        update-types: ["patch", "minor"]

      email:
        patterns:
          - "@react-email/*"
          - "resend"
        update-types: ["patch", "minor"]

      components:
        patterns:
          - "@maskito/*"
          - "@radix-ui/*"
          - "@tailwindcss/*"
          - "@zxcvbn-ts/*"
          - "lucide-react"
          - "motion"
          - "postcss"
          - "react*"
          - "sonner"
          - "tailwind*"
          - "tw-*"
        update-types: ["patch", "minor"]

      convex:
        patterns:
          - "@convex-dev/*"
          - "better-auth"
          - "convex*"
        update-types: ["patch", "minor"]
      
      dev:
        dependency-type: "development"
        patterns:
          - "*"
        update-types: ["patch", "minor"]

      misc:
        dependency-type: "production"
        patterns:
          - "*"
        update-types: ["patch", "minor"]
