import type { PdfFieldType } from "#constants/pdf";

/** Auto-generated from cjp27-petition-to-change-name-of-adult.pdf — do not edit */

export const pdfSchema = {
  county: "text",
  petitionerFirstName: "text",
  petitionerMiddleName: "text",
  petitionerLastName: "text",
  oldFirstName: "text",
  oldMiddleName: "text",
  oldLastName: "text",
  birthplaceCity: "text",
  birthplaceState: "text",
  dateOfBirth: "text",
  residenceStreetAddress: "text",
  residenceSteetAddress2: "text",
  residenceCity: "text",
  residenceState: "text",
  residenceZipCode: "text",
  mailingStreetAddress: "text",
  mailingStreetAddress2: "text",
  mailingCity: "text",
  mailingState: "text",
  mailingZipCode: "text",
  phoneNumber: "text",
  email: "text",
  hasPreviousNameChangeFalse: "checkbox",
  hasPreviousNameChangeTrue: "checkbox",
  previousNameFrom: "text",
  previousNameTo: "text",
  previousNameReason: "text",
  shouldReturnOriginalDocuments: "checkbox",
  hasUsedOtherNameOrAliasFalse: "checkbox",
  hasUsedOtherNameOrAliasTrue: "checkbox",
  otherNamesOrAliases: "text",
  newFirstName: "text",
  newMiddleName: "text",
  newLastName: "text",
  reasonForChangingName: "text",
  hasNoRecordOfOtherStateConvictionsProbationParole: "checkbox",
  isInterpreterNeeded: "checkbox",
  language: "text",
  isOkayToSharePronouns: "checkbox",
  pronouns: "text",
} as const satisfies Record<string, PdfFieldType>;

export type PdfFieldName = keyof typeof pdfSchema;

/** Fields present in the PDF but excluded from the schema */
export const pdfExcludedFields = [
  "form1[0].#pageSet[0].Page1[0].TextField4[0]",
  "form1[0].#pageSet[0].Page1[0].TextField4[1]",
  "form1[0].#pageSet[0].Page2[0].TextField4[0]",
  "form1[0].#pageSet[0].Page2[0].TextField4[1]",
  "form1[0].BodyPage1[0].S10[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S10[0].TextField4[0]",
  "form1[0].BodyPage1[0].S10[0].TextField4[1]",
  "form1[0].BodyPage1[0].S10[0].TextField4[2]",
  "form1[0].BodyPage1[0].S10[0].TextField4[3]",
  "form1[0].BodyPage1[0].S10[0].TextField4[4]",
  "form1[0].BodyPage1[0].S10[0].TextField4[5]",
  "form1[0].BodyPage1[0].S10[0].TextField5[0]",
  "form1[0].BodyPage1[0].S11[0].TextField4[0]",
  "form1[0].BodyPage1[0].S11[0].TextField5[0]",
  "form1[0].BodyPage1[0].S11[0].TextField5[1]",
  "form1[0].BodyPage1[0].S11[0].TextField5[2]",
  "form1[0].BodyPage1[0].S11[0].TextField5[3]",
  "form1[0].BodyPage1[0].S11[0].TextField5[4]",
  "form1[0].BodyPage1[0].S11[0].TextField6[0]",
  "form1[0].BodyPage1[0].S11[0].TextField6[1]",
  "form1[0].BodyPage1[0].S11[0].TextField7[0]",
  "form1[0].BodyPage1[0].S1[0].DocketNo[0]",
  "isAddressCorrectionsSupervisedFacility",
] as const;
