/** Auto-generated from cjp27-petition-to-change-name-of-adult.pdf — do not edit */
import { PDFCheckBox, PDFTextField } from "@cantoo/pdf-lib";

export const pdfSchema = {
  county: PDFTextField,
  petitionerFirstName: PDFTextField,
  petitionerMiddleName: PDFTextField,
  petitionerLastName: PDFTextField,
  oldFirstName: PDFTextField,
  oldMiddleName: PDFTextField,
  oldLastName: PDFTextField,
  birthplaceCity: PDFTextField,
  birthplaceState: PDFTextField,
  dateOfBirth: PDFTextField,
  residenceStreetAddress: PDFTextField,
  residenceSteetAddress2: PDFTextField,
  residenceCity: PDFTextField,
  residenceState: PDFTextField,
  residenceZipCode: PDFTextField,
  mailingStreetAddress: PDFTextField,
  mailingStreetAddress2: PDFTextField,
  mailingCity: PDFTextField,
  mailingState: PDFTextField,
  mailingZipCode: PDFTextField,
  phoneNumber: PDFTextField,
  email: PDFTextField,
  hasPreviousNameChangeFalse: PDFCheckBox,
  hasPreviousNameChangeTrue: PDFCheckBox,
  previousNameFrom: PDFTextField,
  previousNameTo: PDFTextField,
  previousNameReason: PDFTextField,
  shouldReturnOriginalDocuments: PDFCheckBox,
  hasUsedOtherNameOrAliasFalse: PDFCheckBox,
  hasUsedOtherNameOrAliasTrue: PDFCheckBox,
  otherNamesOrAliases: PDFTextField,
  newFirstName: PDFTextField,
  newMiddleName: PDFTextField,
  newLastName: PDFTextField,
  reasonForChangingName: PDFTextField,
  hasNoRecordOfOtherStateConvictionsProbationParole: PDFCheckBox,
  isInterpreterNeeded: PDFCheckBox,
  language: PDFTextField,
  isOkayToSharePronouns: PDFCheckBox,
  pronouns: PDFTextField,
} as const;

export type PdfFieldName = keyof typeof pdfSchema;

/** Fields present in the PDF but excluded from the schema */
export const pdfExcludedFields = [
  "form1[0].#pageSet[0].Page1[0].TextField4[0]",
  "form1[0].#pageSet[0].Page1[0].TextField4[1]",
  "form1[0].#pageSet[0].Page2[0].TextField4[0]",
  "form1[0].#pageSet[0].Page2[0].TextField4[1]",
  "form1[0].BodyPage1[0].S10[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S10[0].TextField4[0]",
  "form1[0].BodyPage1[0].S10[0].TextField4[1]",
  "form1[0].BodyPage1[0].S10[0].TextField4[2]",
  "form1[0].BodyPage1[0].S10[0].TextField4[3]",
  "form1[0].BodyPage1[0].S10[0].TextField4[4]",
  "form1[0].BodyPage1[0].S10[0].TextField4[5]",
  "form1[0].BodyPage1[0].S10[0].TextField5[0]",
  "form1[0].BodyPage1[0].S11[0].TextField4[0]",
  "form1[0].BodyPage1[0].S11[0].TextField5[0]",
  "form1[0].BodyPage1[0].S11[0].TextField5[1]",
  "form1[0].BodyPage1[0].S11[0].TextField5[2]",
  "form1[0].BodyPage1[0].S11[0].TextField5[3]",
  "form1[0].BodyPage1[0].S11[0].TextField5[4]",
  "form1[0].BodyPage1[0].S11[0].TextField6[0]",
  "form1[0].BodyPage1[0].S11[0].TextField6[1]",
  "form1[0].BodyPage1[0].S11[0].TextField7[0]",
  "form1[0].BodyPage1[0].S1[0].DocketNo[0]",
  "isAddressCorrectionsSupervisedFacility",
] as const;
