/** Auto-generated from pc8.1-change-of-name.pdf — do not edit */

export const pdfSchema = {
  currentLegalName: "text",
  residenceStreetAddress: "text",
  residenceCity: "text",
  residenceState: "text",
  residenceZipCode: "text",
  phoneNumber: "text",
  mailingStreetAddress: "text",
  mailingCityStateAndZip: "text",
  email: "text",
  nameOnOriginalBirthRecord: "text",
  dateOfBirth: "text",
  placeOfBirth: "text",
  mothersMaidenName: "text",
  fathersName: "text",
  occupation: "text",
  maritalStatus: "text",
  previousAddress1: "text",
  previousAddress2: "text",
  previousAddress3: "text",
  reasonForNameChange: "text",
  reasonForNameChange2: "text",
  newFirstName: "text",
  newMiddleName: "text",
  newLastName: "text",
  newBirthCertFirstName: "text",
  newBirthCertMiddleName: "text",
  newBirthCertLastName: "text",
} as const;

export type PdfFieldName = keyof typeof pdfSchema;

/** Fields present in the PDF but excluded from the schema */
export const pdfExcludedFields = [
  "2",
  "3",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "5",
  "50",
  "51",
  "52",
  "53",
  "54",
  "Combo Box 1",
  "Combo Box 4",
  "Signature Field 4",
  "sign 2",
  "sign1",
] as const;
