// New York State Department of Public Service county list:
// https://documents.dps.ny.gov/public/Common/SearchCounty.aspx
export const NEW_YORK_COUNTIES = [
  "Albany",
  "Allegany",
  "Bronx",
  "Broome",
  "Cattaraugus",
  "Cayuga",
  "Chautauqua",
  "Chemung",
  "Chenango",
  "Clinton",
  "Columbia",
  "Cortland",
  "Delaware",
  "Dutchess",
  "Erie",
  "Essex",
  "Franklin",
  "Fulton",
  "Genesee",
  "Greene",
  "Hamilton",
  "Herkimer",
  "Jefferson",
  "Kings",
  "Lewis",
  "Livingston",
  "Madison",
  "Monroe",
  "Montgomery",
  "Nassau",
  "New York",
  "Niagara",
  "Oneida",
  "Onondaga",
  "Ontario",
  "Orange",
  "Orleans",
  "Oswego",
  "Otsego",
  "Putnam",
  "Queens",
  "Rensselaer",
  "Richmond",
  "Rockland",
  "St. Lawrence",
  "Saratoga",
  "Schenectady",
  "Schoharie",
  "Schuyler",
  "Seneca",
  "Steuben",
  "Suffolk",
  "Sullivan",
  "Tioga",
  "Tompkins",
  "Ulster",
  "Warren",
  "Washington",
  "Wayne",
  "Westchester",
  "Wyoming",
  "Yates",
] as const;

const COUNTY_BOROUGH_NAMES: Partial<
  Record<(typeof NEW_YORK_COUNTIES)[number], string>
> = {
  Kings: "Brooklyn",
  "New York": "Manhattan",
  Richmond: "Staten Island",
};

export const NEW_YORK_COUNTY_OPTIONS = NEW_YORK_COUNTIES.map((county) => ({
  label: COUNTY_BOROUGH_NAMES[county]
    ? `${county} (${COUNTY_BOROUGH_NAMES[county]})`
    : county,
  value: county,
}));
