/** Auto-generated from lic100-drivers-license-learners-permit-or-id-card.pdf — do not edit */
import { PDFCheckBox, PDFRadioGroup, PDFTextField } from "@cantoo/pdf-lib";

export const pdfSchema = {
  Type: PDFRadioGroup,
  "Document to Issue": PDFRadioGroup,
  "Class of Learner's Permit/License": PDFRadioGroup,
  "Service Type": PDFRadioGroup,
  Name: PDFCheckBox,
  Address: PDFCheckBox,
  DOB: PDFCheckBox,
  "Gender change": PDFCheckBox,
  Height: PDFCheckBox,
  "Eye color": PDFCheckBox,
  "Last Name": PDFTextField,
  "First Name": PDFTextField,
  "Middle Name": PDFTextField,
  Suffix: PDFTextField,
  "Current Massachusetts Learners Permit or Drivers License #": PDFTextField,
  "Date of Birth": PDFTextField,
  "Foreign Passport": PDFCheckBox,
  "Consular ID": PDFCheckBox,
  "Social Security Number": PDFTextField,
  Number: PDFTextField,
  "Country of Issuance": PDFTextField,
  "Have you had a MA permit, license, ID, or registration?": PDFCheckBox,
  "Name and number": PDFTextField,
  "Residential Address - Street": PDFTextField,
  "Residential Address - Apt #": PDFTextField,
  "Residential Address - City": PDFTextField,
  "Residential Address - State": PDFTextField,
  "Residential Address - Zip Code": PDFTextField,
  "same as above": PDFCheckBox,
  "Mailing Address - Street": PDFTextField,
  "Mailing Address - Apt #": PDFTextField,
  "Mailing Address - City": PDFTextField,
  "Mailing Address - State": PDFTextField,
  "Mailing Address - Zip Code": PDFTextField,
  Email: PDFTextField,
  Phone: PDFTextField,
  "Phone Type 1": PDFRadioGroup,
  "Emergency Contact Email": PDFTextField,
  "Emergency Contact Name": PDFTextField,
  "Emergency Contact Phone #": PDFTextField,
  "Phone Type 2": PDFRadioGroup,
  "Drivers License Learners Permit or ID Card": PDFTextField,
  "Restrictions if applicable": PDFTextField,
  "Document Type": PDFRadioGroup,
  Country: PDFTextField,
  State: PDFTextField,
  "Issue Date": PDFTextField,
  "Expiration Date": PDFTextField,
  "Height (feet, inches)": PDFTextField,
  Gender: PDFRadioGroup,
  "Eye Color": PDFRadioGroup,
  "Organ and tissue donor": PDFRadioGroup,
  "Donate to organ and tissue donor fund": PDFRadioGroup,
  "Are you an active duty member": PDFCheckBox,
  "If you are a veteran of the US Armed Forces do you": PDFCheckBox,
  "What military branch": PDFTextField,
  "Are you a veteran": PDFCheckBox,
  "Citizen of the Unites States of America": PDFRadioGroup,
  "License in another state, country, or jurisdiction": PDFRadioGroup,
  "If yes where": PDFTextField,
  "What credential class": PDFTextField,
  "What credential #": PDFTextField,
  "List any current license/permit": PDFTextField,
  "Any impairment": PDFRadioGroup,
  "Any medication": PDFRadioGroup,
  "License suspended": PDFRadioGroup,
  "Person giving consent": PDFRadioGroup,
  "Parent/Guardian's Printed Name": PDFTextField,
  "Parent/Guardian's Address": PDFTextField,
  Date: PDFTextField,
} as const;

export type PdfFieldName = keyof typeof pdfSchema;
