#!/usr/bin/env tsx

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { styleText } from "node:util";
import { listAllPdfs, type PdfEntry } from "../lib/catalog";

const __dirname = dirname(fileURLToPath(import.meta.url));
const UPSTREAM_PDFS_PATH = join(__dirname, "../upstream-pdfs.jsonc");
const GENERATED_COMMENT =
  "// Auto-generated by scripts/check-pdf-drift.ts. Do not edit manually.";
const USER_AGENT =
  "namesake-pdf-monitor/1.0 (+https://github.com/namesakefyi/namesake)";

const PASS = styleText("green", "✓");
const FAIL = styleText("red", "✗");
const SKIP = styleText("yellow", "⊘");

export interface HashEntry {
  url: string;
  hash: string;
  etag?: string;
  title: string;
  checkedAt: string;
}

export type HashStore = Record<string, HashEntry>;

export type FetchResult =
  | { status: "unchanged" }
  | { status: "unverifiable"; reason: string }
  | { status: "new" | "changed"; hash: string; etag?: string }
  | { status: "error"; reason: string };

export interface DriftResult {
  changed: PdfEntry[];
  newlyIndexed: PdfEntry[];
  fetchErrors: Array<{
    id: string;
    title: string;
    canonicalUrl: string;
    reason: string;
  }>;
}

export function computeDrift(
  pdfs: PdfEntry[],
  fetchResults: Map<string, FetchResult>,
): DriftResult {
  const changed: PdfEntry[] = [];
  const newlyIndexed: PdfEntry[] = [];
  const fetchErrors: DriftResult["fetchErrors"] = [];

  for (const pdf of pdfs) {
    if (!pdf.canonicalUrl) continue;
    const result = fetchResults.get(pdf.id);
    if (!result) continue;

    if (result.status === "error") {
      fetchErrors.push({
        id: pdf.id,
        title: pdf.title,
        canonicalUrl: pdf.canonicalUrl,
        reason: result.reason,
      });
    } else if (result.status === "new") {
      newlyIndexed.push(pdf);
    } else if (result.status === "changed") {
      changed.push(pdf);
    }
  }

  return { changed, newlyIndexed, fetchErrors };
}

async function fetchPdfEntry(
  url: string,
  stored?: HashEntry,
): Promise<FetchResult> {
  try {
    const headers: Record<string, string> = { "User-Agent": USER_AGENT };
    if (stored?.etag) headers["If-None-Match"] = stored.etag;

    const res = await fetch(url, {
      redirect: "follow",
      headers,
      signal: AbortSignal.timeout(30_000),
    });

    if (res.status === 304) return { status: "unchanged" };
    if (res.status === 403)
      return { status: "unverifiable", reason: "HTTP 403 (blocked)" };
    if (!res.ok) return { status: "error", reason: `HTTP ${res.status}` };

    const buf = await res.arrayBuffer();
    const hash = `sha256:${createHash("sha256").update(Buffer.from(buf)).digest("hex")}`;
    const etag = res.headers.get("etag") ?? undefined;

    if (!stored || !stored.hash) return { status: "new", hash, etag };
    if (hash === stored.hash) return { status: "unchanged" };
    return { status: "changed", hash, etag };
  } catch (err) {
    return {
      status: "error",
      reason: err instanceof Error ? err.message : String(err),
    };
  }
}

async function* runChecks(
  pdfs: PdfEntry[],
  stored: HashStore,
): AsyncGenerator<{ pdf: PdfEntry; result: FetchResult; ms: number }> {
  for (const pdf of pdfs) {
    const t = performance.now();
    const result = await fetchPdfEntry(pdf.canonicalUrl, stored[pdf.id]);
    yield { pdf, result, ms: Math.round(performance.now() - t) };
  }
}

function formatDuration(ms: number): string {
  return ms < 1000 ? `${ms}ms` : `${(ms / 1000).toFixed(2)}s`;
}

function printResult(pdf: PdfEntry, result: FetchResult, ms: number): void {
  const dur = styleText("dim", formatDuration(ms));
  const url = pdf.canonicalUrl;
  switch (result.status) {
    case "unchanged":
      process.stdout.write(` ${PASS} ${url} ${dur}\n`);
      break;
    case "unverifiable":
      process.stdout.write(
        ` ${SKIP} ${url} ${styleText("yellow", "unverifiable")} ${dur}\n`,
      );
      break;
    case "new":
      process.stdout.write(
        ` ${PASS} ${url} ${styleText("green", "new")} ${dur}\n`,
      );
      break;
    case "changed":
      process.stdout.write(
        ` ${FAIL} ${url} ${styleText(["bold", "yellow"], "changed")} ${dur}\n`,
      );
      break;
    case "error":
      process.stdout.write(
        ` ${FAIL} ${url} ${styleText("red", result.reason)} ${dur}\n`,
      );
      break;
  }
}

function printSummary(
  drift: DriftResult,
  fetchResults: Map<string, FetchResult>,
  pdfs: PdfEntry[],
  totalMs: number,
): void {
  const unverifiableCount = [...fetchResults.values()].filter(
    (r) => r.status === "unverifiable",
  ).length;
  const unchangedCount =
    pdfs.length -
    drift.newlyIndexed.length -
    drift.changed.length -
    drift.fetchErrors.length -
    unverifiableCount;

  const dim = (n: number, label: string) => styleText("gray", `${n} ${label}`);
  const bold = (
    n: number,
    label: string,
    color: Parameters<typeof styleText>[0],
  ) =>
    styleText(
      ["bold", ...(Array.isArray(color) ? color : [color])],
      `${n} ${label}`,
    );

  const newStr =
    drift.newlyIndexed.length === 0
      ? dim(0, "new")
      : bold(drift.newlyIndexed.length, "new", "magenta");

  const unchangedStr =
    unchangedCount === 0
      ? dim(0, "unchanged")
      : bold(unchangedCount, "unchanged", "green");

  const unverifiableStr =
    unverifiableCount === 0
      ? dim(0, "unverifiable")
      : bold(unverifiableCount, "unverifiable", "yellow");

  const changedStr =
    drift.changed.length === 0
      ? dim(0, "changed")
      : bold(drift.changed.length, "changed", "yellow");

  const errorsStr =
    drift.fetchErrors.length === 0
      ? dim(0, "errors")
      : bold(drift.fetchErrors.length, "errors", "red");

  const LABEL_PAD = 10;
  const label = (s: string) => ` ${styleText("gray", s.padStart(LABEL_PAD))}  `;
  const cont = " ".repeat(1 + LABEL_PAD + 2);

  process.stdout.write("\n");
  process.stdout.write(
    `${label("PDF Files")}${newStr}\n${cont}${unchangedStr}\n${cont}${unverifiableStr}\n${cont}${changedStr}\n${cont}${errorsStr}\n`,
  );
  process.stdout.write(`${label("Duration")}${formatDuration(totalMs)}\n`);
  process.stdout.write("\n");
}

async function main() {
  const start = performance.now();

  const stored: HashStore = existsSync(UPSTREAM_PDFS_PATH)
    ? (() => {
        const raw = readFileSync(UPSTREAM_PDFS_PATH, "utf8");
        const json = raw.startsWith("//")
          ? raw.slice(raw.indexOf("\n") + 1)
          : raw;
        return JSON.parse(json);
      })()
    : {};

  const pdfs = listAllPdfs().filter((p) => p.canonicalUrl);
  const fetchResults = new Map<string, FetchResult>();

  for await (const { pdf, result, ms } of runChecks(pdfs, stored)) {
    fetchResults.set(pdf.id, result);
    if (process.stdout.isTTY) printResult(pdf, result, ms);
  }

  let anyUpdated = false;
  for (const pdf of pdfs) {
    const result = fetchResults.get(pdf.id);
    if (
      !result ||
      result.status === "error" ||
      result.status === "unchanged" ||
      result.status === "unverifiable"
    )
      continue;
    stored[pdf.id] = {
      url: pdf.canonicalUrl,
      hash: result.hash,
      ...(result.etag ? { etag: result.etag } : {}),
      title: pdf.title,
      checkedAt: new Date().toISOString(),
    };
    anyUpdated = true;
  }

  if (anyUpdated) {
    writeFileSync(
      UPSTREAM_PDFS_PATH,
      `${GENERATED_COMMENT}\n${JSON.stringify(stored, null, 2)}\n`,
    );
  }

  const drift = computeDrift(pdfs, fetchResults);

  if (process.stdout.isTTY) {
    printSummary(
      drift,
      fetchResults,
      pdfs,
      Math.round(performance.now() - start),
    );
  } else {
    for (const pdf of pdfs) {
      const result = fetchResults.get(pdf.id);
      if (result?.status === "unverifiable") {
        process.stderr.write(
          `[skip] ${pdf.id} (${pdf.canonicalUrl}): ${result.reason}\n`,
        );
      }
    }
    for (const { id, canonicalUrl, reason } of drift.fetchErrors) {
      process.stderr.write(`[warn] ${id} (${canonicalUrl}): ${reason}\n`);
    }
    if (drift.changed.length > 0) {
      const lines = drift.changed
        .map((p) => `- **${p.title}** (\`${p.id}\`): ${p.canonicalUrl}`)
        .join("\n");
      process.stdout.write(
        [
          "## Upstream PDF changes detected",
          "",
          "The following PDFs have changed at their canonical source URLs and may need to be updated:",
          "",
          lines,
          "",
          "Please review each PDF and update the local copy in `web/src/content/pdfs/` if the new version includes relevant changes.",
          "",
        ].join("\n"),
      );
    }
  }

  if (drift.changed.length > 0) process.exit(1);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    process.stderr.write(`[error] ${(err as Error).message}\n`);
    process.exit(2);
  });
}
