name: Feature Request
description: Suggest an idea for Namesake!
labels: ["feature request"]
body:
  - type: textarea
    attributes:
      label: What feature would you like to see?
      description: Provide a clear and concise description of what the problem is. You can attach images or log files by clicking this area to highlight it and then dragging files in.
      value: |
        - **The problem:** I'm always frustrated when [...]
        - **Solution:** I would like to see [...]
        - **Alternatives:** I've also considered [...]
      render: markdown
    validations:
      required: true
