/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Sponsor = {
  _id: string;
  _type: "sponsor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Press = {
  _id: string;
  _type: "press";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  outlet: string;
  url: string;
  date: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type FormReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "form";
};

export type GuideReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "guide";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type StateReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "state";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Form = {
  _id: string;
  _type: "form";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  banner?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          href: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }
      | {
          reference:
            | FormReference
            | GuideReference
            | PageReference
            | PostReference;
          _type: "internalLink";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug: Slug;
  state?: StateReference;
  category: CategoryReference;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Guide = {
  _id: string;
  _type: "guide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  state?: StateReference;
  category: CategoryReference;
  slug: Slug;
  costs?: Array<{
    title?: string;
    amount?: number;
    required?: "required" | "notRequired";
    _type: "cost";
    _key: string;
  }>;
  content?: Array<
    | {
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        cite?: string;
        _type: "blockquote";
        _key: string;
      }
    | {
        placeholder?: string;
        _type: "break";
        _key: string;
      }
    | ({
        _key: string;
      } & GuideReference)
    | {
        summary?: string;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "details";
        _key: string;
      }
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              reference:
                | FormReference
                | GuideReference
                | PageReference
                | PostReference;
              _type: "internalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        width?: number;
        caption?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "image";
        _key: string;
      }
    | {
        url: string;
        _type: "youtube";
        _key: string;
      }
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              reference:
                | FormReference
                | GuideReference
                | PageReference
                | PostReference;
              _type: "internalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        width?: number;
        caption?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "image";
        _key: string;
      }
    | {
        url: string;
        _type: "youtube";
        _key: string;
      }
  >;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  annotation?:
    | "highlight"
    | "underline"
    | "strike-through"
    | "bracket"
    | "circle"
    | "box"
    | "crossed-off";
  color?:
    | "purple"
    | "pink"
    | "blue"
    | "yellow"
    | "green"
    | "brown"
    | "black"
    | "white";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  showDescription: boolean;
  publishDate: string;
  annotation?:
    | "highlight"
    | "underline"
    | "strike-through"
    | "bracket"
    | "circle"
    | "box"
    | "crossed-off";
  authors?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              reference:
                | FormReference
                | GuideReference
                | PageReference
                | PostReference;
              _type: "internalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        cite?: string;
        _type: "blockquote";
        _key: string;
      }
    | {
        placeholder?: string;
        _type: "break";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        width?: number;
        caption?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "image";
        _key: string;
      }
    | {
        url: string;
        _type: "youtube";
        _key: string;
      }
  >;
};

export type State = {
  _id: string;
  _type: "state";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  namesakeSupport: "full" | "prioritized" | "none";
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  description: string;
  states: Array<
    {
      _key: string;
    } & StateReference
  >;
  slug: Slug;
  url: string;
  services: Array<string>;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  officialPartner?: boolean;
  email?: string;
  phone?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  bio: string;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialLinks?: Array<{
    name?: string;
    url?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Sponsor
  | SanityImageCrop
  | SanityImageHotspot
  | Press
  | FormReference
  | GuideReference
  | PageReference
  | PostReference
  | StateReference
  | CategoryReference
  | Form
  | Slug
  | Guide
  | Page
  | AuthorReference
  | Post
  | State
  | Contact
  | Category
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/index.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "page" && (slug.current == "index" || slug.current == "" || !defined(slug))][0]{    _id,    title,    slug,    description,    content[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "reference": @.reference->{_type, slug, title}    }  }},    ogImage,    annotation,    color  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  description: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "form";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "guide";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "page";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "post";
                    slug: Slug;
                    title: string;
                  };
              _type: "internalLink";
              _key: string;
            }
          | {
              href: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        width?: number;
        caption?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "image";
        _key: string;
        markDefs: null;
      }
    | {
        url: string;
        _type: "youtube";
        _key: string;
        markDefs: null;
      }
  > | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  annotation:
    | "box"
    | "bracket"
    | "circle"
    | "crossed-off"
    | "highlight"
    | "strike-through"
    | "underline"
    | null;
  color:
    | "black"
    | "blue"
    | "brown"
    | "green"
    | "pink"
    | "purple"
    | "white"
    | "yellow"
    | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    slug,    description,    content[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "reference": @.reference->{_type, slug, title}    }  }},    ogImage,    annotation,    color  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  description: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "form";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "guide";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "page";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "post";
                    slug: Slug;
                    title: string;
                  };
              _type: "internalLink";
              _key: string;
            }
          | {
              href: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        width?: number;
        caption?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "image";
        _key: string;
        markDefs: null;
      }
    | {
        url: string;
        _type: "youtube";
        _key: string;
        markDefs: null;
      }
  > | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  annotation:
    | "box"
    | "bracket"
    | "circle"
    | "crossed-off"
    | "highlight"
    | "strike-through"
    | "underline"
    | null;
  color:
    | "black"
    | "blue"
    | "brown"
    | "green"
    | "pink"
    | "purple"
    | "white"
    | "yellow"
    | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: POSTS_INDEX_QUERY
// Query: *[_type == "post" && defined(slug) && publishDate <= now()]{    title,    slug,    publishDate,    description,    image,    "authors": authors[]->name  } | order(publishDate desc)
export type POSTS_INDEX_QUERY_RESULT = Array<{
  title: string;
  slug: Slug;
  publishDate: string;
  description: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  authors: Array<string> | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    slug,    publishDate,    description,    showDescription,    image,    annotation,    content[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "reference": @.reference->{_type, slug, title}    }  }},    "authors": authors[]->{      _id,      name,      role,      bio,      avatar,      socialLinks    }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  publishDate: string;
  description: string;
  showDescription: boolean;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  annotation:
    | "box"
    | "bracket"
    | "circle"
    | "crossed-off"
    | "highlight"
    | "strike-through"
    | "underline"
    | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "form";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "guide";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "page";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "post";
                    slug: Slug;
                    title: string;
                  };
              _type: "internalLink";
              _key: string;
            }
          | {
              href: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        cite?: string;
        _type: "blockquote";
        _key: string;
        markDefs: null;
      }
    | {
        placeholder?: string;
        _type: "break";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        width?: number;
        caption?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "image";
        _key: string;
        markDefs: null;
      }
    | {
        url: string;
        _type: "youtube";
        _key: string;
        markDefs: null;
      }
  > | null;
  authors: Array<{
    _id: string;
    name: string;
    role: string;
    bio: string;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    socialLinks: Array<{
      name?: string;
      url?: string;
      _key: string;
    }> | null;
  }> | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: RSS_POSTS_QUERY
// Query: *[_type == "post" && defined(slug) && publishDate <= now()]{    title,    slug,    publishDate,    description,    "contentText": pt::text(content)  } | order(publishDate desc)
export type RSS_POSTS_QUERY_RESULT = Array<{
  title: string;
  slug: Slug;
  publishDate: string;
  description: string;
  contentText: string;
}>;

// Source: src/sanity/queries/index.ts
// Variable: GUIDES_INDEX_QUERY
// Query: *[_type == "guide" && defined(slug)]{    title,    slug,    "state": state->name,    "category": category->name,    _updatedAt,  } | order(publishDate desc)
export type GUIDES_INDEX_QUERY_RESULT = Array<{
  title: string;
  slug: Slug;
  state: string | null;
  category: string;
  _updatedAt: string;
}>;

// Source: src/sanity/queries/index.ts
// Variable: GUIDE_BY_SLUG_QUERY
// Query: *[_type == "guide" && slug.current == $slug][0]{    ...,    content[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      "reference": @.reference->{_type, slug, title}    }  }}  }
export type GUIDE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "guide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  state?: StateReference;
  category: CategoryReference;
  slug: Slug;
  costs?: Array<{
    title?: string;
    amount?: number;
    required?: "notRequired" | "required";
    _type: "cost";
    _key: string;
  }>;
  content: Array<
    | {
        _key: string;
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        markDefs: null;
      }
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "form";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "guide";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "page";
                    slug: Slug;
                    title: string;
                  }
                | {
                    _type: "post";
                    slug: Slug;
                    title: string;
                  };
              _type: "internalLink";
              _key: string;
            }
          | {
              href: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        cite?: string;
        _type: "blockquote";
        _key: string;
        markDefs: null;
      }
    | {
        placeholder?: string;
        _type: "break";
        _key: string;
        markDefs: null;
      }
    | {
        summary?: string;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "details";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        width?: number;
        caption?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                reference:
                  | FormReference
                  | GuideReference
                  | PageReference
                  | PostReference;
                _type: "internalLink";
                _key: string;
              }
            | {
                href: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "image";
        _key: string;
        markDefs: null;
      }
    | {
        url: string;
        _type: "youtube";
        _key: string;
        markDefs: null;
      }
  > | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: FORMS_INDEX_QUERY
// Query: *[_type == "form" && defined(slug)]{    title,    slug,    _updatedAt,  } | order(publishDate desc)
export type FORMS_INDEX_QUERY_RESULT = Array<{
  title: string;
  slug: Slug;
  _updatedAt: string;
}>;

// Source: src/sanity/queries/index.ts
// Variable: FORM_BY_SLUG_QUERY
// Query: *[_type == "form" && slug.current == $slug][0]
export type FORM_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "form";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  banner?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          reference:
            | FormReference
            | GuideReference
            | PageReference
            | PostReference;
          _type: "internalLink";
          _key: string;
        }
      | {
          href: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug: Slug;
  state?: StateReference;
  category: CategoryReference;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: FORM_BY_SLUG_WITH_GUIDE_COSTS_QUERY
// Query: *[_type == "form" && slug.current == $slug][0]{    title,    description,    banner,    _updatedAt,    state,    category,    "costs": *[_type == "guide" && state._ref == ^.state._ref && category._ref == ^.category._ref][0].costs  }
export type FORM_BY_SLUG_WITH_GUIDE_COSTS_QUERY_RESULT = {
  title: string;
  description: string | null;
  banner: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          reference:
            | FormReference
            | GuideReference
            | PageReference
            | PostReference;
          _type: "internalLink";
          _key: string;
        }
      | {
          href: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  _updatedAt: string;
  state: StateReference | null;
  category: CategoryReference;
  costs: Array<{
    title?: string;
    amount?: number;
    required?: "notRequired" | "required";
    _type: "cost";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: DOCUMENT_REFERENCE_BY_ID_QUERY
// Query: *[_id == $ref]{_type, slug, title}[0]
export type DOCUMENT_REFERENCE_BY_ID_QUERY_RESULT =
  | {
      _type: "author";
      slug: null;
      title: null;
    }
  | {
      _type: "category";
      slug: Slug;
      title: null;
    }
  | {
      _type: "contact";
      slug: Slug;
      title: null;
    }
  | {
      _type: "form";
      slug: Slug;
      title: string;
    }
  | {
      _type: "guide";
      slug: Slug;
      title: string;
    }
  | {
      _type: "page";
      slug: Slug;
      title: string;
    }
  | {
      _type: "post";
      slug: Slug;
      title: string;
    }
  | {
      _type: "press";
      slug: null;
      title: string;
    }
  | {
      _type: "sanity.fileAsset";
      slug: null;
      title: string | null;
    }
  | {
      _type: "sanity.imageAsset";
      slug: null;
      title: string | null;
    }
  | {
      _type: "sponsor";
      slug: null;
      title: null;
    }
  | {
      _type: "state";
      slug: Slug;
      title: null;
    }
  | null;

// Source: src/sanity/queries/index.ts
// Variable: GUIDE_COSTS_BY_ID_QUERY
// Query: *[_type == "guide" && _id == $_ref][0]{    costs  }
export type GUIDE_COSTS_BY_ID_QUERY_RESULT = {
  costs: Array<{
    title?: string;
    amount?: number;
    required?: "notRequired" | "required";
    _type: "cost";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: PRESS_ARTICLES_QUERY
// Query: *[_type == "press"]{    _id,    title,    outlet,    url,    date,    image  } | order(date desc)
export type PRESS_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  outlet: string;
  url: string;
  date: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: STATES_SUPPORT_QUERY
// Query: *[_type == "state"]{    name,    "slug": slug.current,    namesakeSupport  }
export type STATES_SUPPORT_QUERY_RESULT = Array<{
  name: string;
  slug: string;
  namesakeSupport: "full" | "none" | "prioritized";
}>;

// Source: src/sanity/queries/index.ts
// Variable: SPONSORS_QUERY
// Query: *[_type == "sponsor"]
export type SPONSORS_QUERY_RESULT = Array<{
  _id: string;
  _type: "sponsor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url: string;
}>;

// Source: src/sanity/queries/index.ts
// Variable: DIRECTORY_FILTER_STATES_QUERY
// Query: *[_type == "state" && defined(slug)] | order(name asc) {    name,    "slug": slug.current  }
export type DIRECTORY_FILTER_STATES_QUERY_RESULT = Array<{
  name: string;
  slug: string;
}>;

// Source: src/sanity/queries/index.ts
// Variable: DIRECTORY_CONTACTS_LIST_QUERY
// Query: *[    _type == "contact" &&    defined(slug) &&    ($stateSlug == "" || $stateSlug in states[]->slug.current) &&    ($service == "" || $service in services)  ] {    name,    "slug": slug.current,    description,    "states": states[]->name | order(@ asc),    services,    logo,    email,    phone,    url,    officialPartner,  } | order(officialPartner desc, name asc)
export type DIRECTORY_CONTACTS_LIST_QUERY_RESULT = Array<{
  name: string;
  slug: string;
  description: string;
  states: Array<string>;
  services: Array<string>;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  email: string | null;
  phone: string | null;
  url: string;
  officialPartner: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "page" && (slug.current == "index" || slug.current == "" || !defined(slug))][0]{\n    _id,\n    title,\n    slug,\n    description,\n    content[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == "internalLink" => {\n      ...,\n      "reference": @.reference->{_type, slug, title}\n    }\n  }\n},\n    ogImage,\n    annotation,\n    color\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    description,\n    content[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == "internalLink" => {\n      ...,\n      "reference": @.reference->{_type, slug, title}\n    }\n  }\n},\n    ogImage,\n    annotation,\n    color\n  }\n': PAGE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug) && publishDate <= now()]{\n    title,\n    slug,\n    publishDate,\n    description,\n    image,\n    "authors": authors[]->name\n  } | order(publishDate desc)\n': POSTS_INDEX_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    publishDate,\n    description,\n    showDescription,\n    image,\n    annotation,\n    content[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == "internalLink" => {\n      ...,\n      "reference": @.reference->{_type, slug, title}\n    }\n  }\n},\n    "authors": authors[]->{\n      _id,\n      name,\n      role,\n      bio,\n      avatar,\n      socialLinks\n    }\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug) && publishDate <= now()]{\n    title,\n    slug,\n    publishDate,\n    description,\n    "contentText": pt::text(content)\n  } | order(publishDate desc)\n': RSS_POSTS_QUERY_RESULT;
    '\n  *[_type == "guide" && defined(slug)]{\n    title,\n    slug,\n    "state": state->name,\n    "category": category->name,\n    _updatedAt,\n  } | order(publishDate desc)\n': GUIDES_INDEX_QUERY_RESULT;
    '\n  *[_type == "guide" && slug.current == $slug][0]{\n    ...,\n    content[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == "internalLink" => {\n      ...,\n      "reference": @.reference->{_type, slug, title}\n    }\n  }\n}\n  }\n': GUIDE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "form" && defined(slug)]{\n    title,\n    slug,\n    _updatedAt,\n  } | order(publishDate desc)\n': FORMS_INDEX_QUERY_RESULT;
    '\n  *[_type == "form" && slug.current == $slug][0]\n': FORM_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "form" && slug.current == $slug][0]{\n    title,\n    description,\n    banner,\n    _updatedAt,\n    state,\n    category,\n    "costs": *[_type == "guide" && state._ref == ^.state._ref && category._ref == ^.category._ref][0].costs\n  }\n': FORM_BY_SLUG_WITH_GUIDE_COSTS_QUERY_RESULT;
    "\n  *[_id == $ref]{_type, slug, title}[0]\n": DOCUMENT_REFERENCE_BY_ID_QUERY_RESULT;
    '\n  *[_type == "guide" && _id == $_ref][0]{\n    costs\n  }\n': GUIDE_COSTS_BY_ID_QUERY_RESULT;
    '\n  *[_type == "press"]{\n    _id,\n    title,\n    outlet,\n    url,\n    date,\n    image\n  } | order(date desc)\n': PRESS_ARTICLES_QUERY_RESULT;
    '\n  *[_type == "state"]{\n    name,\n    "slug": slug.current,\n    namesakeSupport\n  }\n': STATES_SUPPORT_QUERY_RESULT;
    '*[_type == "sponsor"]': SPONSORS_QUERY_RESULT;
    '\n  *[_type == "state" && defined(slug)] | order(name asc) {\n    name,\n    "slug": slug.current\n  }\n': DIRECTORY_FILTER_STATES_QUERY_RESULT;
    '\n  *[\n    _type == "contact" &&\n    defined(slug) &&\n    ($stateSlug == "" || $stateSlug in states[]->slug.current) &&\n    ($service == "" || $service in services)\n  ] {\n    name,\n    "slug": slug.current,\n    description,\n    "states": states[]->name | order(@ asc),\n    services,\n    logo,\n    email,\n    phone,\n    url,\n    officialPartner,\n  } | order(officialPartner desc, name asc)\n': DIRECTORY_CONTACTS_LIST_QUERY_RESULT;
  }
}
