/** Auto-generated from affidavit-of-indigency.pdf — do not edit */
import { PDFCheckBox, PDFTextField } from "@cantoo/pdf-lib";

export const pdfSchema = {
  courtName: PDFTextField,
  caseNameAndNumber: PDFTextField,
  applicantName: PDFTextField,
  residenceStreetAddress: PDFTextField,
  residenceCity: PDFTextField,
  residenceStateAndZip: PDFTextField,
  isReceivingPublicAssistance: PDFCheckBox,
  isReceivingTAFDC: PDFCheckBox,
  isReceivingMedicaid: PDFCheckBox,
  isReceivingEAEDC: PDFCheckBox,
  isReceivingSSI: PDFCheckBox,
  isReceivingVeteransBenefits: PDFCheckBox,
  dollarAmount: PDFTextField,
  isUnderPovertyLevel: PDFCheckBox,
  perWeek: PDFCheckBox,
  biweekly: PDFCheckBox,
  perMonth: PDFCheckBox,
  perYear: PDFCheckBox,
  householdSize: PDFTextField,
  numberOfDependents: PDFTextField,
  otherHouseholdIncome: PDFTextField,
  isUnableToPay: PDFCheckBox,
  shouldWaiveFilingFeeAndSurcharge: PDFCheckBox,
  filingFeeAndSurcharge: PDFTextField,
  shouldWaiveFilingFeeAndSurchargeForAppeal: PDFCheckBox,
  filingFeeAndSurchargeForAppeal: PDFTextField,
  shouldWaiveFeesForCourtSummons: PDFCheckBox,
  feesForCourtSummons: PDFTextField,
  shouldWaiveOtherFeesSection2: PDFCheckBox,
  otherFeesSection2: PDFTextField,
  otherFeesSection2Details: PDFTextField,
  applySubstitutionSection2: PDFCheckBox,
  substitutionDetailsSection2: PDFTextField,
  shouldWaiveExpertServices: PDFCheckBox,
  costOfExpertServices: PDFTextField,
  expertServicesDetails: PDFTextField,
  shouldWaiveCostOfTranscription: PDFCheckBox,
  costOfTranscription: PDFTextField,
  shouldWaiveRecordingOfTrialForAppeal: PDFCheckBox,
  shouldWaiveAppealBond: PDFCheckBox,
  shouldWaiveCostOfWrittenTranscriptPreparation: PDFCheckBox,
  costOfWrittenTranscriptPreparation: PDFTextField,
  shouldWaiveOtherFeesSection3: PDFCheckBox,
  otherFeesSection3: PDFTextField,
  otherFeesSection3Details: PDFTextField,
  applySubstitutionSection3: PDFCheckBox,
  substitutionDetailsSection3: PDFTextField,
} as const;

export type PdfFieldName = keyof typeof pdfSchema;

/** Fields present in the PDF but excluded from the schema */
export const pdfExcludedFields = [
  "dateSigned",
  "lower cost paid for by the state Check all that apply and in any",
  "signature",
] as const;
