import type { PdfFieldType } from "#constants/pdf";

/** Auto-generated from lic100-drivers-license-learners-permit-or-id-card.pdf — do not edit */

export const pdfSchema = {
  Type: "radio",
  "Document to Issue": "radio",
  "Class of Learner's Permit/License": "radio",
  "Service Type": "radio",
  Name: "checkbox",
  Address: "checkbox",
  DOB: "checkbox",
  "Gender change": "checkbox",
  Height: "checkbox",
  "Eye color": "checkbox",
  "Last Name": "text",
  "First Name": "text",
  "Middle Name": "text",
  Suffix: "text",
  "Current Massachusetts Learners Permit or Drivers License #": "text",
  "Date of Birth": "text",
  "Social Security Number": "text",
  "Foreign Passport": "checkbox",
  Number: "text",
  "Consular ID": "checkbox",
  "Country of Issuance": "text",
  "Name and number": "text",
  "Have you had a MA permit, license, ID, or registration?": "checkbox",
  "Residential Address - Street": "text",
  "Residential Address - Apt #": "text",
  "Residential Address - City": "text",
  "Residential Address - State": "text",
  "Residential Address - Zip Code": "text",
  "Mailing Address - Street": "text",
  "same as above": "checkbox",
  "Mailing Address - Apt #": "text",
  "Mailing Address - City": "text",
  "Mailing Address - State": "text",
  "Mailing Address - Zip Code": "text",
  Email: "text",
  "Phone Type 1": "radio",
  Phone: "text",
  "Emergency Contact Email": "text",
  "Emergency Contact Name": "text",
  "Phone Type 2": "radio",
  "Emergency Contact Phone #": "text",
  "Drivers License Learners Permit or ID Card": "text",
  "Document Type": "radio",
  "Restrictions if applicable": "text",
  Country: "text",
  State: "text",
  "Issue Date": "text",
  "Expiration Date": "text",
  Gender: "radio",
  "Eye Color": "radio",
  "Height (feet, inches)": "text",
  "Organ and tissue donor": "radio",
  "Donate to organ and tissue donor fund": "radio",
  "Are you an active duty member": "checkbox",
  "If you are a veteran of the US Armed Forces do you": "checkbox",
  "Are you a veteran": "checkbox",
  "What military branch": "text",
  "Citizen of the Unites States of America": "radio",
  "License in another state, country, or jurisdiction": "radio",
  "If yes where": "text",
  "What credential class": "text",
  "What credential #": "text",
  "List any current license/permit": "text",
  "Any impairment": "radio",
  "Any medication": "radio",
  "License suspended": "radio",
  "Person giving consent": "radio",
  "Parent/Guardian's Printed Name": "text",
  "Parent/Guardian's Address": "text",
  Date: "text",
} as const satisfies Record<string, PdfFieldType>;

export type PdfFieldName = keyof typeof pdfSchema;
