import { definePdf } from "../../utils/definePdf";
import pdf from "./pc8.1-change-of-name.pdf";
import type { PdfFieldName } from "./schema";

export default definePdf<PdfFieldName>({
  id: "pc8.1-change-of-name",
  title: "Change of Name",
  code: "PC-8.1",
  jurisdiction: "RI",
  pdfPath: pdf,
  resolver: (data) => ({
    // TODO: Map fields to form data
    "Combo Box 1": undefined,
    "2": undefined,
    "Combo Box 4": undefined,
    "3": undefined,
    "5": undefined,
    "6": undefined,
    "7": undefined,
    "8": undefined,
    "9": undefined,
    "10": undefined,
    "11": undefined,
    "12": undefined,
    "13": undefined,
    "15": undefined,
    "17": undefined,
    "18": undefined,
    "19": undefined,
    "20": undefined,
    "21": undefined,
    "22": undefined,
    "23": undefined,
    "24": undefined,
    "25": undefined,
    "26": undefined,
    "27": undefined,
    "28": undefined,
    "29": undefined,
    "30": undefined,
    "31": undefined,
    "32": undefined,
    "33": undefined,
    "34": undefined,
    sign1: undefined,
    "35": undefined,
    "36": undefined,
    "37": undefined,
    "38": undefined,
    "39": undefined,
    "40": undefined,
    "sign 2": undefined,
    "41": undefined,
    "42": undefined,
    "43": undefined,
    "44": undefined,
    "45": undefined,
    "46": undefined,
    "47": undefined,
    "48": undefined,
    "49": undefined,
    "50": undefined,
    "51": undefined,
    "52": undefined,
    "53": undefined,
    "54": undefined,
    "Signature Field 4": undefined,
  }),
});
