/** Auto-generated from pc8.1-change-of-name.pdf — do not edit */
import { PDFTextField } from "@cantoo/pdf-lib";

export const pdfSchema = {
  currentLegalName: PDFTextField,
  residenceStreetAddress: PDFTextField,
  residenceCity: PDFTextField,
  residenceState: PDFTextField,
  residenceZipCode: PDFTextField,
  phoneNumber: PDFTextField,
  mailingStreetAddress: PDFTextField,
  mailingCityStateAndZip: PDFTextField,
  email: PDFTextField,
  nameOnOriginalBirthRecord: PDFTextField,
  dateOfBirth: PDFTextField,
  placeOfBirth: PDFTextField,
  mothersMaidenName: PDFTextField,
  fathersName: PDFTextField,
  occupation: PDFTextField,
  maritalStatus: PDFTextField,
  previousAddress1: PDFTextField,
  previousAddress2: PDFTextField,
  previousAddress3: PDFTextField,
  reasonForNameChange: PDFTextField,
  reasonForNameChange2: PDFTextField,
  newFirstName: PDFTextField,
  newMiddleName: PDFTextField,
  newLastName: PDFTextField,
  newBirthCertFirstName: PDFTextField,
  newBirthCertMiddleName: PDFTextField,
  newBirthCertLastName: PDFTextField,
} as const;

export type PdfFieldName = keyof typeof pdfSchema;

/** Fields present in the PDF but excluded from the schema */
export const pdfExcludedFields = [
  "2",
  "3",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "5",
  "50",
  "51",
  "52",
  "53",
  "54",
  "Combo Box 1",
  "Combo Box 4",
  "Signature Field 4",
  "sign 2",
  "sign1",
] as const;
