/** Auto-generated from cjp25-petition-to-change-name-of-minor.pdf — do not edit */
import { PDFCheckBox, PDFTextField } from "@cantoo/pdf-lib";

export const pdfSchema = {
  county: PDFTextField,
  petitionerFirstName: PDFTextField,
  petitionerMiddleName: PDFTextField,
  petitionerLastName: PDFTextField,
  oldFirstName: PDFTextField,
  oldMiddleName: PDFTextField,
  oldLastName: PDFTextField,
  isPresentedByLegalParent1: PDFCheckBox,
  isPresentedByLegalParent2: PDFCheckBox,
  isPresentedByLegalParent3: PDFCheckBox,
  isPresentedByCourtAppointedGuardian: PDFCheckBox,
  dateOfBirth: PDFTextField,
  currentAge: PDFTextField,
  mailingStreetAddress: PDFTextField,
  mailingStreetAddress2: PDFTextField,
  mailingCity: PDFTextField,
  mailingState: PDFTextField,
  mailingZipCode: PDFTextField,
  isUnderSupervisionOfMassDeptOfYouthServices: PDFCheckBox,
  hasPreviousNameChangeFalse: PDFCheckBox,
  hasPreviousNameChangeTrue: PDFCheckBox,
  previousNameFrom: PDFTextField,
  previousNameTo: PDFTextField,
  previousNameReason: PDFTextField,
  shouldReturnOriginalDocuments: PDFCheckBox,
  parent1FirstName: PDFTextField,
  parent1MiddleName: PDFTextField,
  parent1LastName: PDFTextField,
  parent1StreetAddress: PDFTextField,
  parent1StreetAddress2: PDFTextField,
  parent1City: PDFTextField,
  parent1State: PDFTextField,
  parent1ZipCode: PDFTextField,
  parent1Phone: PDFTextField,
  parent1Email: PDFTextField,
  parent2FirstName: PDFTextField,
  parent2MiddleName: PDFTextField,
  parent2LastName: PDFTextField,
  parent2StreetAddress: PDFTextField,
  parent2StreetAddress2: PDFTextField,
  parent2City: PDFTextField,
  parent2State: PDFTextField,
  parent2ZipCode: PDFTextField,
  parent2Phone: PDFTextField,
  parent2Email: PDFTextField,
  parent3FirstName: PDFTextField,
  parent3MiddleName: PDFTextField,
  parent3LastName: PDFTextField,
  parent3StreetAddress: PDFTextField,
  parent3StreetAddress2: PDFTextField,
  parent3City: PDFTextField,
  parent3State: PDFTextField,
  parent3ZipCode: PDFTextField,
  phoneNumber: PDFTextField,
  email: PDFTextField,
  isOnlyOneParentListedOnBirthCertificate: PDFCheckBox,
  isALegalParentDeceased: PDFCheckBox,
  hasLegalParentHadParentalRightsTerminated: PDFCheckBox,
  hasCountAppointedGuardianFalse: PDFCheckBox,
  hasCourtAppointedGuardianTrue: PDFCheckBox,
  guardianFirstName: PDFTextField,
  guardianMiddleName: PDFTextField,
  guardianLastName: PDFTextField,
  guardianStreetAddress: PDFTextField,
  guardianStreetAddress2: PDFTextField,
  guardianCity: PDFTextField,
  guardianState: PDFTextField,
  guardianZipCode: PDFTextField,
  guardianPhone: PDFTextField,
  guardianEmail: PDFTextField,
  coGuardianFirstName: PDFTextField,
  coGuardianMiddleName: PDFTextField,
  coGuardianLastName: PDFTextField,
  coGuardianStreetAddress: PDFTextField,
  coGuardianStreetAddress2: PDFTextField,
  coGuardianCity: PDFTextField,
  coGuardianState: PDFTextField,
  coGuardianZipCode: PDFTextField,
  coGuardianPhone: PDFTextField,
  coGuardianEmail: PDFTextField,
  isChildUnder12: PDFCheckBox,
  isParent1AssentingTrue: PDFCheckBox,
  isParent1AssentingFalse: PDFCheckBox,
  parent1DissentReason: PDFTextField,
  isParent2AssentingTrue: PDFCheckBox,
  isParent2AssentingFalse: PDFCheckBox,
  parent2DissentReason: PDFTextField,
  isParent3AssentingTrue: PDFCheckBox,
  isParent3AssentingFalse: PDFCheckBox,
  parent3DissentReason: PDFTextField,
  isAllGuardiansAssentingTrue: PDFCheckBox,
  isAllGuardiansAssentingFalse: PDFCheckBox,
  guardianDissentReason: PDFTextField,
  newFirstName: PDFTextField,
  newMiddleName: PDFTextField,
  newLastName: PDFTextField,
  reasonForChangingName: PDFTextField,
  isInterpreterNeededForChild: PDFCheckBox,
  isInterpreterNeededForParent1: PDFCheckBox,
  isInterpreterNeededForParent2: PDFCheckBox,
  isInterpreterNeededForParent3: PDFCheckBox,
  isInterpreterNeededForGuardian: PDFCheckBox,
  languages: PDFTextField,
  isOkayToSharePronouns: PDFCheckBox,
  pronouns: PDFTextField,
} as const;

export type PdfFieldName = keyof typeof pdfSchema;

/** Fields present in the PDF but excluded from the schema */
export const pdfExcludedFields = [
  "form1[0].#pageSet[0].Page1[0].TextField4[0]",
  "form1[0].#pageSet[0].Page1[0].TextField4[1]",
  "form1[0].#pageSet[0].Page2[0].TextField4[0]",
  "form1[0].#pageSet[0].Page2[0].TextField4[1]",
  "form1[0].#pageSet[0].Page2[1].TextField4[0]",
  "form1[0].#pageSet[0].Page2[1].TextField4[1]",
  "form1[0].#pageSet[0].Page2[2].TextField4[0]",
  "form1[0].#pageSet[0].Page2[2].TextField4[1]",
  "form1[0].#pageSet[0].Page2[3].TextField4[0]",
  "form1[0].#pageSet[0].Page2[3].TextField4[1]",
  "form1[0].BodyPage1[0].S12[0].TextField4[0]",
  "form1[0].BodyPage1[0].S12[0].TextField5[0]",
  "form1[0].BodyPage1[0].S12[0].TextField5[1]",
  "form1[0].BodyPage1[0].S12[0].TextField5[2]",
  "form1[0].BodyPage1[0].S12[0].TextField5[3]",
  "form1[0].BodyPage1[0].S12[0].TextField5[4]",
  "form1[0].BodyPage1[0].S12[0].TextField6[0]",
  "form1[0].BodyPage1[0].S12[0].TextField6[1]",
  "form1[0].BodyPage1[0].S12[0].TextField7[0]",
  "form1[0].BodyPage1[0].S19[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S19[0].S20[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[0]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[1]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[2]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[3]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[4]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[5]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField5[0]",
  "form1[0].BodyPage1[0].S19[0].TextField4[0]",
  "form1[0].BodyPage1[0].S19[0].TextField4[1]",
  "form1[0].BodyPage1[0].S19[0].TextField4[2]",
  "form1[0].BodyPage1[0].S19[0].TextField4[3]",
  "form1[0].BodyPage1[0].S19[0].TextField4[4]",
  "form1[0].BodyPage1[0].S19[0].TextField4[5]",
  "form1[0].BodyPage1[0].S19[0].TextField5[0]",
  "form1[0].BodyPage1[0].S1[0].DocketNo[0]",
  "form1[0].BodyPage1[0].S20[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S20[0].TextField4[0]",
  "form1[0].BodyPage1[0].S20[0].TextField4[1]",
  "form1[0].BodyPage1[0].S20[0].TextField4[2]",
  "form1[0].BodyPage1[0].S20[0].TextField4[3]",
  "form1[0].BodyPage1[0].S20[0].TextField4[4]",
  "form1[0].BodyPage1[0].S20[0].TextField4[5]",
  "form1[0].BodyPage1[0].S20[0].TextField5[0]",
  "form1[0].BodyPage1[0].S21[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S21[0].TextField4[0]",
  "form1[0].BodyPage1[0].S21[0].TextField4[1]",
  "form1[0].BodyPage1[0].S21[0].TextField4[2]",
  "form1[0].BodyPage1[0].S21[0].TextField4[3]",
  "form1[0].BodyPage1[0].S21[0].TextField4[4]",
  "form1[0].BodyPage1[0].S21[0].TextField4[5]",
  "form1[0].BodyPage1[0].S21[0].TextField5[0]",
  "form1[0].BodyPage1[0].S22[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S22[0].TextField4[0]",
  "form1[0].BodyPage1[0].S22[0].TextField4[1]",
  "form1[0].BodyPage1[0].S22[0].TextField4[2]",
  "form1[0].BodyPage1[0].S22[0].TextField4[3]",
  "form1[0].BodyPage1[0].S22[0].TextField4[4]",
  "form1[0].BodyPage1[0].S22[0].TextField4[5]",
  "form1[0].BodyPage1[0].S22[0].TextField5[0]",
] as const;
