import type { PdfFieldType } from "#constants/pdf";

/** Auto-generated from cjp25-petition-to-change-name-of-minor.pdf — do not edit */

export const pdfSchema = {
  county: "text",
  petitionerFirstName: "text",
  petitionerMiddleName: "text",
  petitionerLastName: "text",
  oldFirstName: "text",
  oldMiddleName: "text",
  oldLastName: "text",
  isPresentedByLegalParent1: "checkbox",
  isPresentedByLegalParent2: "checkbox",
  isPresentedByLegalParent3: "checkbox",
  isPresentedByCourtAppointedGuardian: "checkbox",
  dateOfBirth: "text",
  currentAge: "text",
  mailingStreetAddress: "text",
  mailingStreetAddress2: "text",
  mailingCity: "text",
  mailingState: "text",
  mailingZipCode: "text",
  isUnderSupervisionOfMassDeptOfYouthServices: "checkbox",
  hasPreviousNameChangeFalse: "checkbox",
  hasPreviousNameChangeTrue: "checkbox",
  previousNameFrom: "text",
  previousNameTo: "text",
  previousNameReason: "text",
  shouldReturnOriginalDocuments: "checkbox",
  parent1FirstName: "text",
  parent1MiddleName: "text",
  parent1LastName: "text",
  parent1StreetAddress: "text",
  parent1StreetAddress2: "text",
  parent1City: "text",
  parent1State: "text",
  parent1ZipCode: "text",
  parent1Phone: "text",
  parent1Email: "text",
  parent2FirstName: "text",
  parent2MiddleName: "text",
  parent2LastName: "text",
  parent2StreetAddress: "text",
  parent2StreetAddress2: "text",
  parent2City: "text",
  parent2State: "text",
  parent2ZipCode: "text",
  parent2Phone: "text",
  parent2Email: "text",
  parent3FirstName: "text",
  parent3MiddleName: "text",
  parent3LastName: "text",
  parent3StreetAddress: "text",
  parent3StreetAddress2: "text",
  parent3City: "text",
  parent3State: "text",
  parent3ZipCode: "text",
  phoneNumber: "text",
  email: "text",
  isOnlyOneParentListedOnBirthCertificate: "checkbox",
  isALegalParentDeceased: "checkbox",
  hasLegalParentHadParentalRightsTerminated: "checkbox",
  hasCountAppointedGuardianFalse: "checkbox",
  hasCourtAppointedGuardianTrue: "checkbox",
  guardianFirstName: "text",
  guardianMiddleName: "text",
  guardianLastName: "text",
  guardianStreetAddress: "text",
  guardianStreetAddress2: "text",
  guardianCity: "text",
  guardianState: "text",
  guardianZipCode: "text",
  guardianPhone: "text",
  guardianEmail: "text",
  coGuardianFirstName: "text",
  coGuardianMiddleName: "text",
  coGuardianLastName: "text",
  coGuardianStreetAddress: "text",
  coGuardianStreetAddress2: "text",
  coGuardianCity: "text",
  coGuardianState: "text",
  coGuardianZipCode: "text",
  coGuardianPhone: "text",
  coGuardianEmail: "text",
  isChildUnder12: "checkbox",
  isParent1AssentingTrue: "checkbox",
  isParent1AssentingFalse: "checkbox",
  parent1DissentReason: "text",
  isParent2AssentingTrue: "checkbox",
  isParent2AssentingFalse: "checkbox",
  parent2DissentReason: "text",
  isParent3AssentingTrue: "checkbox",
  isParent3AssentingFalse: "checkbox",
  parent3DissentReason: "text",
  isAllGuardiansAssentingTrue: "checkbox",
  isAllGuardiansAssentingFalse: "checkbox",
  guardianDissentReason: "text",
  newFirstName: "text",
  newMiddleName: "text",
  newLastName: "text",
  reasonForChangingName: "text",
  isInterpreterNeededForChild: "checkbox",
  isInterpreterNeededForParent1: "checkbox",
  isInterpreterNeededForParent2: "checkbox",
  isInterpreterNeededForParent3: "checkbox",
  isInterpreterNeededForGuardian: "checkbox",
  languages: "text",
  isOkayToSharePronouns: "checkbox",
  pronouns: "text",
} as const satisfies Record<string, PdfFieldType>;

export type PdfFieldName = keyof typeof pdfSchema;

/** Fields present in the PDF but excluded from the schema */
export const pdfExcludedFields = [
  "form1[0].#pageSet[0].Page1[0].TextField4[0]",
  "form1[0].#pageSet[0].Page1[0].TextField4[1]",
  "form1[0].#pageSet[0].Page2[0].TextField4[0]",
  "form1[0].#pageSet[0].Page2[0].TextField4[1]",
  "form1[0].#pageSet[0].Page2[1].TextField4[0]",
  "form1[0].#pageSet[0].Page2[1].TextField4[1]",
  "form1[0].#pageSet[0].Page2[2].TextField4[0]",
  "form1[0].#pageSet[0].Page2[2].TextField4[1]",
  "form1[0].#pageSet[0].Page2[3].TextField4[0]",
  "form1[0].#pageSet[0].Page2[3].TextField4[1]",
  "form1[0].BodyPage1[0].S12[0].TextField4[0]",
  "form1[0].BodyPage1[0].S12[0].TextField5[0]",
  "form1[0].BodyPage1[0].S12[0].TextField5[1]",
  "form1[0].BodyPage1[0].S12[0].TextField5[2]",
  "form1[0].BodyPage1[0].S12[0].TextField5[3]",
  "form1[0].BodyPage1[0].S12[0].TextField5[4]",
  "form1[0].BodyPage1[0].S12[0].TextField6[0]",
  "form1[0].BodyPage1[0].S12[0].TextField6[1]",
  "form1[0].BodyPage1[0].S12[0].TextField7[0]",
  "form1[0].BodyPage1[0].S19[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S19[0].S20[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[0]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[1]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[2]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[3]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[4]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField4[5]",
  "form1[0].BodyPage1[0].S19[0].S20[0].TextField5[0]",
  "form1[0].BodyPage1[0].S19[0].TextField4[0]",
  "form1[0].BodyPage1[0].S19[0].TextField4[1]",
  "form1[0].BodyPage1[0].S19[0].TextField4[2]",
  "form1[0].BodyPage1[0].S19[0].TextField4[3]",
  "form1[0].BodyPage1[0].S19[0].TextField4[4]",
  "form1[0].BodyPage1[0].S19[0].TextField4[5]",
  "form1[0].BodyPage1[0].S19[0].TextField5[0]",
  "form1[0].BodyPage1[0].S1[0].DocketNo[0]",
  "form1[0].BodyPage1[0].S20[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S20[0].TextField4[0]",
  "form1[0].BodyPage1[0].S20[0].TextField4[1]",
  "form1[0].BodyPage1[0].S20[0].TextField4[2]",
  "form1[0].BodyPage1[0].S20[0].TextField4[3]",
  "form1[0].BodyPage1[0].S20[0].TextField4[4]",
  "form1[0].BodyPage1[0].S20[0].TextField4[5]",
  "form1[0].BodyPage1[0].S20[0].TextField5[0]",
  "form1[0].BodyPage1[0].S21[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S21[0].TextField4[0]",
  "form1[0].BodyPage1[0].S21[0].TextField4[1]",
  "form1[0].BodyPage1[0].S21[0].TextField4[2]",
  "form1[0].BodyPage1[0].S21[0].TextField4[3]",
  "form1[0].BodyPage1[0].S21[0].TextField4[4]",
  "form1[0].BodyPage1[0].S21[0].TextField4[5]",
  "form1[0].BodyPage1[0].S21[0].TextField5[0]",
  "form1[0].BodyPage1[0].S22[0].DateTimeField3[0]",
  "form1[0].BodyPage1[0].S22[0].TextField4[0]",
  "form1[0].BodyPage1[0].S22[0].TextField4[1]",
  "form1[0].BodyPage1[0].S22[0].TextField4[2]",
  "form1[0].BodyPage1[0].S22[0].TextField4[3]",
  "form1[0].BodyPage1[0].S22[0].TextField4[4]",
  "form1[0].BodyPage1[0].S22[0].TextField4[5]",
  "form1[0].BodyPage1[0].S22[0].TextField5[0]",
] as const;
