/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UnauthenticatedSigninRouteImport } from './routes/_unauthenticated/signin'
import { Route as UnauthenticatedResetPasswordRouteImport } from './routes/_unauthenticated/reset-password'
import { Route as UnauthenticatedGoodbyeRouteImport } from './routes/_unauthenticated/goodbye'
import { Route as UnauthenticatedForgotRouteImport } from './routes/_unauthenticated/forgot'
import { Route as AuthenticatedSignoutRouteImport } from './routes/_authenticated/signout'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/_home'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedDocumentsRouteRouteImport } from './routes/_authenticated/documents/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/_home/index'
import { Route as AuthenticatedSettingsResponsesRouteImport } from './routes/_authenticated/settings/responses'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedFormsSocialSecurityRouteImport } from './routes/_authenticated/forms/social-security'
import { Route as AuthenticatedFormsMaCourtOrderRouteImport } from './routes/_authenticated/forms/ma-court-order'
import { Route as AuthenticatedDocumentsPdfIdRouteImport } from './routes/_authenticated/documents/$pdfId'
import { Route as AuthenticatedAdminQuestsIndexRouteImport } from './routes/_authenticated/admin/quests.index'
import { Route as AuthenticatedHomeQuestsIndexRouteImport } from './routes/_authenticated/_home/quests/index'
import { Route as AuthenticatedHomeQuestsGettingStartedRouteImport } from './routes/_authenticated/_home/quests/getting-started'
import { Route as AuthenticatedHomeQuestsQuestSlugRouteRouteImport } from './routes/_authenticated/_home/quests/$questSlug/route'
import { Route as AuthenticatedHomeQuestsQuestSlugIndexRouteImport } from './routes/_authenticated/_home/quests/$questSlug/index'
import { Route as AuthenticatedHomeQuestsQuestSlugEditRouteImport } from './routes/_authenticated/_home/quests/$questSlug/edit'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedSigninRoute = UnauthenticatedSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const UnauthenticatedResetPasswordRoute =
  UnauthenticatedResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedGoodbyeRoute = UnauthenticatedGoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const UnauthenticatedForgotRoute = UnauthenticatedForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedSignoutRoute = AuthenticatedSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsRouteRoute =
  AuthenticatedDocumentsRouteRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDocumentsRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHomeRoute,
} as any)
const AuthenticatedSettingsResponsesRoute =
  AuthenticatedSettingsResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedFormsSocialSecurityRoute =
  AuthenticatedFormsSocialSecurityRouteImport.update({
    id: '/forms/social-security',
    path: '/forms/social-security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormsMaCourtOrderRoute =
  AuthenticatedFormsMaCourtOrderRouteImport.update({
    id: '/forms/ma-court-order',
    path: '/forms/ma-court-order',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsPdfIdRoute =
  AuthenticatedDocumentsPdfIdRouteImport.update({
    id: '/$pdfId',
    path: '/$pdfId',
    getParentRoute: () => AuthenticatedDocumentsRouteRoute,
  } as any)
const AuthenticatedAdminQuestsIndexRoute =
  AuthenticatedAdminQuestsIndexRouteImport.update({
    id: '/quests/',
    path: '/quests/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedHomeQuestsIndexRoute =
  AuthenticatedHomeQuestsIndexRouteImport.update({
    id: '/quests/',
    path: '/quests/',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)
const AuthenticatedHomeQuestsGettingStartedRoute =
  AuthenticatedHomeQuestsGettingStartedRouteImport.update({
    id: '/quests/getting-started',
    path: '/quests/getting-started',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)
const AuthenticatedHomeQuestsQuestSlugRouteRoute =
  AuthenticatedHomeQuestsQuestSlugRouteRouteImport.update({
    id: '/quests/$questSlug',
    path: '/quests/$questSlug',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)
const AuthenticatedHomeQuestsQuestSlugIndexRoute =
  AuthenticatedHomeQuestsQuestSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHomeQuestsQuestSlugRouteRoute,
  } as any)
const AuthenticatedHomeQuestsQuestSlugEditRoute =
  AuthenticatedHomeQuestsQuestSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedHomeQuestsQuestSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/signout': typeof AuthenticatedSignoutRoute
  '/forgot': typeof UnauthenticatedForgotRoute
  '/goodbye': typeof UnauthenticatedGoodbyeRoute
  '/reset-password': typeof UnauthenticatedResetPasswordRoute
  '/signin': typeof UnauthenticatedSigninRoute
  '/documents/$pdfId': typeof AuthenticatedDocumentsPdfIdRoute
  '/forms/ma-court-order': typeof AuthenticatedFormsMaCourtOrderRoute
  '/forms/social-security': typeof AuthenticatedFormsSocialSecurityRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/responses': typeof AuthenticatedSettingsResponsesRoute
  '/': typeof AuthenticatedHomeIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/quests/$questSlug': typeof AuthenticatedHomeQuestsQuestSlugRouteRouteWithChildren
  '/quests/getting-started': typeof AuthenticatedHomeQuestsGettingStartedRoute
  '/quests': typeof AuthenticatedHomeQuestsIndexRoute
  '/admin/quests': typeof AuthenticatedAdminQuestsIndexRoute
  '/quests/$questSlug/edit': typeof AuthenticatedHomeQuestsQuestSlugEditRoute
  '/quests/$questSlug/': typeof AuthenticatedHomeQuestsQuestSlugIndexRoute
}
export interface FileRoutesByTo {
  '/signout': typeof AuthenticatedSignoutRoute
  '/forgot': typeof UnauthenticatedForgotRoute
  '/goodbye': typeof UnauthenticatedGoodbyeRoute
  '/reset-password': typeof UnauthenticatedResetPasswordRoute
  '/signin': typeof UnauthenticatedSigninRoute
  '/documents/$pdfId': typeof AuthenticatedDocumentsPdfIdRoute
  '/forms/ma-court-order': typeof AuthenticatedFormsMaCourtOrderRoute
  '/forms/social-security': typeof AuthenticatedFormsSocialSecurityRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/responses': typeof AuthenticatedSettingsResponsesRoute
  '/': typeof AuthenticatedHomeIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/quests/getting-started': typeof AuthenticatedHomeQuestsGettingStartedRoute
  '/quests': typeof AuthenticatedHomeQuestsIndexRoute
  '/admin/quests': typeof AuthenticatedAdminQuestsIndexRoute
  '/quests/$questSlug/edit': typeof AuthenticatedHomeQuestsQuestSlugEditRoute
  '/quests/$questSlug': typeof AuthenticatedHomeQuestsQuestSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/_home': typeof AuthenticatedHomeRouteWithChildren
  '/_authenticated/signout': typeof AuthenticatedSignoutRoute
  '/_unauthenticated/forgot': typeof UnauthenticatedForgotRoute
  '/_unauthenticated/goodbye': typeof UnauthenticatedGoodbyeRoute
  '/_unauthenticated/reset-password': typeof UnauthenticatedResetPasswordRoute
  '/_unauthenticated/signin': typeof UnauthenticatedSigninRoute
  '/_authenticated/documents/$pdfId': typeof AuthenticatedDocumentsPdfIdRoute
  '/_authenticated/forms/ma-court-order': typeof AuthenticatedFormsMaCourtOrderRoute
  '/_authenticated/forms/social-security': typeof AuthenticatedFormsSocialSecurityRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/responses': typeof AuthenticatedSettingsResponsesRoute
  '/_authenticated/_home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/_home/quests/$questSlug': typeof AuthenticatedHomeQuestsQuestSlugRouteRouteWithChildren
  '/_authenticated/_home/quests/getting-started': typeof AuthenticatedHomeQuestsGettingStartedRoute
  '/_authenticated/_home/quests/': typeof AuthenticatedHomeQuestsIndexRoute
  '/_authenticated/admin/quests/': typeof AuthenticatedAdminQuestsIndexRoute
  '/_authenticated/_home/quests/$questSlug/edit': typeof AuthenticatedHomeQuestsQuestSlugEditRoute
  '/_authenticated/_home/quests/$questSlug/': typeof AuthenticatedHomeQuestsQuestSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/documents'
    | '/settings'
    | '/signout'
    | '/forgot'
    | '/goodbye'
    | '/reset-password'
    | '/signin'
    | '/documents/$pdfId'
    | '/forms/ma-court-order'
    | '/forms/social-security'
    | '/settings/account'
    | '/settings/responses'
    | '/'
    | '/admin/'
    | '/documents/'
    | '/settings/'
    | '/quests/$questSlug'
    | '/quests/getting-started'
    | '/quests'
    | '/admin/quests'
    | '/quests/$questSlug/edit'
    | '/quests/$questSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signout'
    | '/forgot'
    | '/goodbye'
    | '/reset-password'
    | '/signin'
    | '/documents/$pdfId'
    | '/forms/ma-court-order'
    | '/forms/social-security'
    | '/settings/account'
    | '/settings/responses'
    | '/'
    | '/admin'
    | '/documents'
    | '/settings'
    | '/quests/getting-started'
    | '/quests'
    | '/admin/quests'
    | '/quests/$questSlug/edit'
    | '/quests/$questSlug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/admin'
    | '/_authenticated/documents'
    | '/_authenticated/settings'
    | '/_authenticated/_home'
    | '/_authenticated/signout'
    | '/_unauthenticated/forgot'
    | '/_unauthenticated/goodbye'
    | '/_unauthenticated/reset-password'
    | '/_unauthenticated/signin'
    | '/_authenticated/documents/$pdfId'
    | '/_authenticated/forms/ma-court-order'
    | '/_authenticated/forms/social-security'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/responses'
    | '/_authenticated/_home/'
    | '/_authenticated/admin/'
    | '/_authenticated/documents/'
    | '/_authenticated/settings/'
    | '/_authenticated/_home/quests/$questSlug'
    | '/_authenticated/_home/quests/getting-started'
    | '/_authenticated/_home/quests/'
    | '/_authenticated/admin/quests/'
    | '/_authenticated/_home/quests/$questSlug/edit'
    | '/_authenticated/_home/quests/$questSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/signin': {
      id: '/_unauthenticated/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof UnauthenticatedSigninRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/reset-password': {
      id: '/_unauthenticated/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof UnauthenticatedResetPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/goodbye': {
      id: '/_unauthenticated/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof UnauthenticatedGoodbyeRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/forgot': {
      id: '/_unauthenticated/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof UnauthenticatedForgotRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/signout': {
      id: '/_authenticated/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof AuthenticatedSignoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_home': {
      id: '/_authenticated/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedDocumentsRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_home/': {
      id: '/_authenticated/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/settings/responses': {
      id: '/_authenticated/settings/responses'
      path: '/responses'
      fullPath: '/settings/responses'
      preLoaderRoute: typeof AuthenticatedSettingsResponsesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/forms/social-security': {
      id: '/_authenticated/forms/social-security'
      path: '/forms/social-security'
      fullPath: '/forms/social-security'
      preLoaderRoute: typeof AuthenticatedFormsSocialSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms/ma-court-order': {
      id: '/_authenticated/forms/ma-court-order'
      path: '/forms/ma-court-order'
      fullPath: '/forms/ma-court-order'
      preLoaderRoute: typeof AuthenticatedFormsMaCourtOrderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/$pdfId': {
      id: '/_authenticated/documents/$pdfId'
      path: '/$pdfId'
      fullPath: '/documents/$pdfId'
      preLoaderRoute: typeof AuthenticatedDocumentsPdfIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRouteRoute
    }
    '/_authenticated/admin/quests/': {
      id: '/_authenticated/admin/quests/'
      path: '/quests'
      fullPath: '/admin/quests'
      preLoaderRoute: typeof AuthenticatedAdminQuestsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_home/quests/': {
      id: '/_authenticated/_home/quests/'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AuthenticatedHomeQuestsIndexRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/_home/quests/getting-started': {
      id: '/_authenticated/_home/quests/getting-started'
      path: '/quests/getting-started'
      fullPath: '/quests/getting-started'
      preLoaderRoute: typeof AuthenticatedHomeQuestsGettingStartedRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/_home/quests/$questSlug': {
      id: '/_authenticated/_home/quests/$questSlug'
      path: '/quests/$questSlug'
      fullPath: '/quests/$questSlug'
      preLoaderRoute: typeof AuthenticatedHomeQuestsQuestSlugRouteRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/_home/quests/$questSlug/': {
      id: '/_authenticated/_home/quests/$questSlug/'
      path: '/'
      fullPath: '/quests/$questSlug/'
      preLoaderRoute: typeof AuthenticatedHomeQuestsQuestSlugIndexRouteImport
      parentRoute: typeof AuthenticatedHomeQuestsQuestSlugRouteRoute
    }
    '/_authenticated/_home/quests/$questSlug/edit': {
      id: '/_authenticated/_home/quests/$questSlug/edit'
      path: '/edit'
      fullPath: '/quests/$questSlug/edit'
      preLoaderRoute: typeof AuthenticatedHomeQuestsQuestSlugEditRouteImport
      parentRoute: typeof AuthenticatedHomeQuestsQuestSlugRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminQuestsIndexRoute: typeof AuthenticatedAdminQuestsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminQuestsIndexRoute: AuthenticatedAdminQuestsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDocumentsRouteRouteChildren {
  AuthenticatedDocumentsPdfIdRoute: typeof AuthenticatedDocumentsPdfIdRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
}

const AuthenticatedDocumentsRouteRouteChildren: AuthenticatedDocumentsRouteRouteChildren =
  {
    AuthenticatedDocumentsPdfIdRoute: AuthenticatedDocumentsPdfIdRoute,
    AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  }

const AuthenticatedDocumentsRouteRouteWithChildren =
  AuthenticatedDocumentsRouteRoute._addFileChildren(
    AuthenticatedDocumentsRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsResponsesRoute: typeof AuthenticatedSettingsResponsesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsResponsesRoute: AuthenticatedSettingsResponsesRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedHomeQuestsQuestSlugRouteRouteChildren {
  AuthenticatedHomeQuestsQuestSlugEditRoute: typeof AuthenticatedHomeQuestsQuestSlugEditRoute
  AuthenticatedHomeQuestsQuestSlugIndexRoute: typeof AuthenticatedHomeQuestsQuestSlugIndexRoute
}

const AuthenticatedHomeQuestsQuestSlugRouteRouteChildren: AuthenticatedHomeQuestsQuestSlugRouteRouteChildren =
  {
    AuthenticatedHomeQuestsQuestSlugEditRoute:
      AuthenticatedHomeQuestsQuestSlugEditRoute,
    AuthenticatedHomeQuestsQuestSlugIndexRoute:
      AuthenticatedHomeQuestsQuestSlugIndexRoute,
  }

const AuthenticatedHomeQuestsQuestSlugRouteRouteWithChildren =
  AuthenticatedHomeQuestsQuestSlugRouteRoute._addFileChildren(
    AuthenticatedHomeQuestsQuestSlugRouteRouteChildren,
  )

interface AuthenticatedHomeRouteChildren {
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedHomeQuestsQuestSlugRouteRoute: typeof AuthenticatedHomeQuestsQuestSlugRouteRouteWithChildren
  AuthenticatedHomeQuestsGettingStartedRoute: typeof AuthenticatedHomeQuestsGettingStartedRoute
  AuthenticatedHomeQuestsIndexRoute: typeof AuthenticatedHomeQuestsIndexRoute
}

const AuthenticatedHomeRouteChildren: AuthenticatedHomeRouteChildren = {
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedHomeQuestsQuestSlugRouteRoute:
    AuthenticatedHomeQuestsQuestSlugRouteRouteWithChildren,
  AuthenticatedHomeQuestsGettingStartedRoute:
    AuthenticatedHomeQuestsGettingStartedRoute,
  AuthenticatedHomeQuestsIndexRoute: AuthenticatedHomeQuestsIndexRoute,
}

const AuthenticatedHomeRouteWithChildren =
  AuthenticatedHomeRoute._addFileChildren(AuthenticatedHomeRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDocumentsRouteRoute: typeof AuthenticatedDocumentsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRouteWithChildren
  AuthenticatedSignoutRoute: typeof AuthenticatedSignoutRoute
  AuthenticatedFormsMaCourtOrderRoute: typeof AuthenticatedFormsMaCourtOrderRoute
  AuthenticatedFormsSocialSecurityRoute: typeof AuthenticatedFormsSocialSecurityRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDocumentsRouteRoute:
    AuthenticatedDocumentsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRouteWithChildren,
  AuthenticatedSignoutRoute: AuthenticatedSignoutRoute,
  AuthenticatedFormsMaCourtOrderRoute: AuthenticatedFormsMaCourtOrderRoute,
  AuthenticatedFormsSocialSecurityRoute: AuthenticatedFormsSocialSecurityRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedForgotRoute: typeof UnauthenticatedForgotRoute
  UnauthenticatedGoodbyeRoute: typeof UnauthenticatedGoodbyeRoute
  UnauthenticatedResetPasswordRoute: typeof UnauthenticatedResetPasswordRoute
  UnauthenticatedSigninRoute: typeof UnauthenticatedSigninRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedForgotRoute: UnauthenticatedForgotRoute,
  UnauthenticatedGoodbyeRoute: UnauthenticatedGoodbyeRoute,
  UnauthenticatedResetPasswordRoute: UnauthenticatedResetPasswordRoute,
  UnauthenticatedSigninRoute: UnauthenticatedSigninRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
