import { definePdf } from "#lib/pdfs/definePdf";
import type { PdfFieldName } from "./schema";
import pdf from "./ucsnc1-name-change-and-or-sex-designation-change-petition-for-individual-adult.pdf";

export default definePdf<PdfFieldName>({
  id: "ucsnc1-name-change-and-or-sex-designation-change-petition-for-individual-adult",
  title:
    "Name Change and/or Sex Designation Change Petition for Individual Adult",
  code: "UCS-NC1",
  jurisdiction: "ny",
  canonicalUrl: "https://www.nycourts.gov/media/32631",
  pdfPath: pdf,
  resolver: (data) => ({
    // TODO: Map fields to form data
    Reset_Form: undefined,
    SealingRequest: undefined,
    ConvictedOfCrime: undefined,
    "SealingRequest-specify": undefined,
    "ReasonsForNameChangeRequest-specify": undefined,
    CourtOfConviction: undefined,
    CourtType: undefined,
    Crime: undefined,
    County: undefined,
    Bankruptcy: undefined,
    PetitionerName: undefined,
    IndexNumber: undefined,
    JudgmentsOrLiens: undefined,
    PartyToAction: undefined,
    SupportingDocument: undefined,
    NameChange: undefined,
    SexDesignationChange: undefined,
    "BankruptcyJudgmentsLiensParty-specify": undefined,
    "SupportingDocument-specify": undefined,
    NewSexDesignation: undefined,
    PreviousSexDesignationChangeRequest: undefined,
    "PreviousSexDesignationChangeRequest-specify": undefined,
    CurrentlyMarried: undefined,
    PreviouslyMarried: undefined,
    ChildrenUnder21: undefined,
    ReasonsForSexDesignationChangeRequest: undefined,
    ChildSupport: undefined,
    SignatureDate: undefined,
    ChildSupportPayments: undefined,
    "ReasonsForSexDesignationChangeRequest-specify": undefined,
    ChildSupportArrears: undefined,
    NewName: undefined,
    CourtIssuingChildSupportOrder: undefined,
    AffirmDay: undefined,
    AffirmMonth: undefined,
    SupportCollectionsUnit: undefined,
    AffirmYear: undefined,
    PlaceOfBirth: undefined,
    SpousalSupport: undefined,
    SpousalSupportPayments: undefined,
    SpousalSupportArrears: undefined,
    CourtIssuingSpousalSupportOrder: undefined,
    PreviousNameChangePetition: undefined,
    PreviousNameChangePetition0: undefined,
    Age: undefined,
    DOB: undefined,
    Print_Form: undefined,
    "PreviousNameChagePetition-specify": undefined,
    CurrentAddress: undefined,
  }),
});
