/** Auto-generated from ucsnc1-name-change-and-or-sex-designation-change-petition-for-individual-adult.pdf — do not edit */

import type { PdfFieldType } from "#constants/pdf";

export const pdfSchema = {
  Reset_Form: "button",
  SealingRequest: "radio",
  ConvictedOfCrime: "radio",
  "SealingRequest-specify": "text",
  reasonForChangingName: "text",
  CourtOfConviction: "text",
  CourtType: "text",
  Crime: "text",
  county: "text",
  Bankruptcy: "radio",
  currentLegalName: "text",
  IndexNumber: "text",
  JudgmentsOrLiens: "radio",
  PartyToAction: "radio",
  SupportingDocument: "radio",
  NameChange: "checkbox",
  SexDesignationChange: "checkbox",
  "BankruptcyJudgmentsLiensParty-specify": "text",
  "SupportingDocument-specify": "text",
  newGender: "text",
  PreviousSexDesignationChangeRequest: "radio",
  "PreviousSexDesignationChangeRequest-specify": "text",
  CurrentlyMarried: "radio",
  PreviouslyMarried: "radio",
  ChildrenUnder21: "radio",
  ReasonsForSexDesignationChangeRequest: "radio",
  ChildSupport: "radio",
  SignatureDate: "text",
  ChildSupportPayments: "radio",
  "ReasonsForSexDesignationChangeRequest-specify": "text",
  ChildSupportArrears: "text",
  newFullName: "text",
  CourtIssuingChildSupportOrder: "text",
  AffirmDay: "text",
  AffirmMonth: "text",
  SupportCollectionsUnit: "text",
  AffirmYear: "text",
  placeOfBirth: "text",
  SpousalSupport: "radio",
  SpousalSupportPayments: "radio",
  SpousalSupportArrears: "text",
  CourtIssuingSpousalSupportOrder: "text",
  PreviousNameChangePetition: "radio",
  PreviousNameChangePetition0: "radio",
  currentAge: "text",
  dateOfBirth: "text",
  Print_Form: "button",
  "PreviousNameChagePetition-specify": "text",
  residenceAddress: "text",
} as const satisfies Record<string, PdfFieldType>;

export type PdfFieldName = keyof typeof pdfSchema;
