import type { PdfFieldType } from "#constants/pdf";

/** Auto-generated from ucsnc1-name-change-and-or-sex-designation-change-petition-for-individual-adult.pdf — do not edit */

export const pdfSchema = {
  Reset_Form: "button",
  SealingRequest: "radio",
  "SealingRequest-specify": "text",
  courtType: "text",
  courtCounty: "text",
  oldName: "text",
  indexNumber: "text",
  SupportingDocument: "radio",
  shouldChangeName: "checkbox",
  shouldChangeSexDesignation: "checkbox",
  newName: "text",
  birthplace: "text",
  SpousalSupportPayments: "radio",
  PreviousNameChangePetition: "radio",
  Print_Form: "button",
  hasConviction: "radio",
  courtOfConviction: "text",
  crime: "text",
  hasBankruptcy: "radio",
  hasJudgementsOrLiens: "radio",
  partyToAction: "radio",
  partyToActionDetails: "text",
  currentlyMarried: "radio",
  previouslyMarried: "radio",
  childrenUnder21: "radio",
  childSupport: "radio",
  childSupportPayments: "radio",
  childSupportOwed: "text",
  courtIssuingChildSupportOrder: "text",
  childSupportCollectionsUnit: "text",
  spousalSupport: "radio",
  spousalSupportOwed: "text",
  courtIssuingSpousalSupportOrder: "text",
  hasPreviousNameChange: "radio",
  previousNameReason: "text",
  reasonForChangingName: "text",
  newSex: "text",
  previousSexDesignationChangePetition: "radio",
  previousSexDesignationChangePetitionReason: "text",
  providesSexChangeDesignationReason: "radio",
  sexChangeDesignationReason: "text",
  age: "text",
  dateOfBirth: "text",
  residenceAddress: "text",
  supportingDocumentsDescription: "text",
  signatureDate: "text",
  signatureDay: "text",
  signatureMonth: "text",
  signatureYearEnding: "text",
} as const satisfies Record<string, PdfFieldType>;

export type PdfFieldName = keyof typeof pdfSchema;
