name: Storybook

on:
  pull_request:
    branches: main
  push:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Deploy to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install
          build_command: pnpm build-storybook
          path: storybook-static
          checkout: false
